# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    required_providers {
        random = {
            source = "hashicorp/random"
            version = "3.4.3"
        }
        tfe = {
      source = "hashicorp/tfe"
      version = "0.41.0"
    }
    }
}
